### ISSUE TITLE
cannot join server

### ISSUE THREAD

**Issue by darealHeroBrine** [trulyno/star-technology#174]
i can not join the server i hosted with the server pack i get a itemstackingredient cannot be made with an empty ingredient every time i try to join the server.

**Comment by trulyno** [comment]
i do not need the address. i need the logs to see the error
please edit the message so people dont abuse it

**Comment by darealHeroBrine** [comment]
there i will send the log rightnow
[latest.log](https://github.com/user-attachments/files/17917680/latest.log)

**Comment by trulyno** [comment]
ok the server log has nothing. maybe the player log has something and it is a client side error?

**Comment by darealHeroBrine** [comment]
[latest_player.log](https://github.com/user-attachments/files/17919519/latest.log)

**Comment by darealHeroBrine** [comment]
Found anything?

**Comment by darealHeroBrine** [comment]
I think i found the error? i just rejoined the server and copied this form the logs as its the most recint part

`[16:12:48] [Netty Client IO #1/ERROR]:Error reading recipe from packet.java.lang.IllegalArgumentException: ItemStackIngredients cannot be created using the empty ingredient.
	at igentuman.nc.recipes.ingredient.creator.ItemStackIngredientCreator.from(ItemStackIngredientCreator.java:46) ~[NuclearCraft-1.20.1-1.0.0-rc.2.jar%23436!/:1.0.0-rc.2]
	at igentuman.nc.recipes.ingredient.creator.ItemStackIngredientCreator.read(ItemStackIngredientCreator.java:57) ~[NuclearCraft-1.20.1-1.0.0-rc.2.jar%23436!/:1.0.0-rc.2]
	at igentuman.nc.recipes.ingredient.creator.ItemStackIngredientCreator.read(ItemStackIngredientCreator.java:33) ~[NuclearCraft-1.20.1-1.0.0-rc.2.jar%23436!/:1.0.0-rc.2]
	at igentuman.nc.recipes.serializers.NcRecipeSerializer.readIngredients(NcRecipeSerializer.java:163) ~[NuclearCraft-1.20.1-1.0.0-rc.2.jar%23436!/:1.0.0-rc.2]
	at igentuman.nc.recipes.serializers.NcRecipeSerializer.fromNetwork(NcRecipeSerializer.java:186) ~[NuclearCraft-1.20.1-1.0.0-rc.2.jar%23436!/:1.0.0-rc.2]
	at igentuman.nc.recipes.serializers.NcRecipeSerializer.m_8005_(NcRecipeSerializer.java:27) ~[NuclearCraft-1.20.1-1.0.0-rc.2.jar%23436!/:1.0.0-rc.2]
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_133647_(ClientboundUpdateRecipesPacket.java:45) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?]
	at net.minecraft.network.FriendlyByteBuf.m_236838_(FriendlyByteBuf.java:211) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?]
	at net.minecraft.network.FriendlyByteBuf.m_236845_(FriendlyByteBuf.java:227) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.<init>(ClientboundUpdateRecipesPacket.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?]
	at net.minecraft.network.ConnectionProtocol$PacketSet.m_178327_(ConnectionProtocol.java:459) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?]
	at net.minecraft.network.ConnectionProtocol.m_178321_(ConnectionProtocol.java:522) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?]
	at net.minecraftforge.network.filters.VanillaPacketSplitter.onClientPacket(VanillaPacketSplitter.java:143) ~[forge-1.20.1-47.3.10-universal.jar%23487!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.20.1-47.3.10-universal.jar%23487!/:?]
	at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:80) ~[forge-1.20.1-47.3.10-universal.jar%23487!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
		at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.m_5797_(ClientboundCustomPayloadPacket.java:7) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?]
	at net.minecraft.network.Connection.m_129517_(Connection.java:174) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?]
	at net.minecraft.network.Connection.channelRead0(Connection.java:159) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?]
	at net.minecraft.network.Connection.channelRead0(Connection.java:50) ~[client-1.20.1-20230612.114412-srg.jar%23482!/:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar%23122!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar%23122!/:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar%23122!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar%23122!/:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar%23122!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar%23122!/:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[netty-codec-4.1.82.Final.jar%23122!/:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444) ~[netty-codec-4.1.82.Final.jar%23122!/:4.1.82.Final]
	
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-codec-4.1.82.Final.jar%23122!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar%23122!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.82.Final.jar%23124!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.82.Final.jar%23128!/:4.1.82.Final]
	`

**Comment by darealHeroBrine** [comment]
i didnt mean to close it

**Comment by Nat-thapas** [comment]
I feel like this part is relevant?
```
[01:49:23] [KubeJS Recipe Event Worker 0/ERROR]: An error occurred while reading cucumber-tags.json
java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:101) ~[gson-2.10.jar%23107!/:?]
	at com.blakebr0.cucumber.crafting.TagMapper.getItemForTag(TagMapper.java:121) ~[Cucumber-1.20.1-7.0.12.jar%23359!/:7.0.12]
	at com.blakebr0.cucumber.crafting.TagMapper.getItemStackForTag(TagMapper.java:148) ~[Cucumber-1.20.1-7.0.12.jar%23359!/:7.0.12]
	at com.blakebr0.cucumber.crafting.OutputResolver$Tag.resolve(OutputResolver.java:24) ~[Cucumber-1.20.1-7.0.12.jar%23359!/:7.0.12]
	at com.blakebr0.cucumber.crafting.recipe.ShapedTagRecipe.m_8043_(ShapedTagRecipe.java:34) ~[Cucumber-1.20.1-7.0.12.jar%23359!/:7.0.12]
	at dev.latvian.mods.kubejs.recipe.JsonRecipeJS.hasOutput(JsonRecipeJS.java:39) ~[kubejs-forge-2001.6.5-build.14.jar%23416!/:2001.6.5-build.14]
	at dev.latvian.mods.kubejs.recipe.filter.OutputFilter.test(OutputFilter.java:15) ~[kubejs-forge-2001.6.5-build.14.jar%23416!/:2001.6.5-build.14]
	at dev.latvian.mods.kubejs.recipe.RecipesEventJS$RecipeStreamFilter.test(RecipesEventJS.java:498) ~[kubejs-forge-2001.6.5-build.14.jar%23416!/:2001.6.5-build.14]
	at dev.latvian.mods.kubejs.recipe.RecipesEventJS$RecipeStreamFilter.test(RecipesEventJS.java:495) ~[kubejs-forge-2001.6.5-build.14.jar%23416!/:2001.6.5-build.14]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[?:?]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```
I can't see this error in my own logs, so it definitely isn't one of the normal errors. If this is actually the cause then it points to a file corruption, so you can try reinstalling the modpack on the client side and hopefully that fixes it.

**Comment by trulyno** [comment]
It seems to be a bug cause by NuclearCraft. If you are playing on 1.20.1 Delta Hotfix 5, NuclearCraft is alread redundant and set for removal. If you want to remove the mod(to escape the issue) you need to:
1. Remove the jar file of NuclearCraft from both server and client
2. Remove the following files for both server and client: 
kubejs/server_scripts/nuclear.js
kubejs/server_scripts/gregification/nuclearcraft.js
3. Go into kubejs/server_scripts/tags.js in both server and client and delete all lines starting from line 11

**Comment by darealHeroBrine** [comment]
it is still an issue btw
