### ISSUE TITLE
Nuclearcraft crashes

### ISSUE THREAD

**Issue by kmod** [trulyno/star-technology#71]
I've gotten into a couple crash loops (ie crashes on load, have to revert to backup) after starting with Nuclearcraft. The first was related to the reactor port, which would crash whenever I looked at it:

<details>
<summary>Traceback</summary>

```
java.lang.ClassCastException: class igentuman.nc.block.entity.fission.FissionCasingBE cannot be cast to class igentuman.nc.block.entity.fission.FissionControllerBE (igentuman.nc.block.entity.fission.FissionCasingBE and igentuman.nc.block.entity.fission.FissionControllerBE are in module nuclearcraft@1.0.3 of loader 'TRANSFORMER' @de579ff)
	at igentuman.nc.block.entity.fission.FissionPortBE.controller(FissionPortBE.java:194) ~[NuclearCraft-1.19.2-1.0.3.jar%23424!/:1.0.3] {re:classloading}
	at igentuman.nc.block.entity.fission.FissionPortBE.getCapability(FissionPortBE.java:122) ~[NuclearCraft-1.19.2-1.0.3.jar%23424!/:1.0.3] {re:classloading}
	at com.gregtechceu.gtceu.api.capability.GTCapabilityHelper.getBlockEntityCapability(GTCapabilityHelper.java:112) ~[gtceu-1.19.2-1.2.3.a.jar%23389!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.capability.GTCapabilityHelper.getCoverable(GTCapabilityHelper.java:46) ~[gtceu-1.19.2-1.2.3.a.jar%23389!/:?] {re:classloading}
	at com.gregtechceu.gtceu.client.renderer.BlockHighLightRenderer.renderBlockHighLight(BlockHighLightRenderer.java:112) ~[gtceu-1.19.2-1.2.3.a.jar%23389!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.gregtechceu.gtceu.client.forge.ForgeClientEventListener.onBlockHighlightEvent(ForgeClientEventListener.java:45) ~[gtceu-1.19.2-1.2.3.a.jar%23389!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.gregtechceu.gtceu.client.forge.__ForgeClientEventListener_onBlockHighlightEvent_Block.invoke(.dynamic) ~[gtceu-1.19.2-1.2.3.a.jar%23389!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onDrawHighlight(ForgeHooksClient.java:261) ~[forge-1.19.2-43.3.9-universal.jar%23472!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1325) ~[client-1.19.2-20220805.130853-srg.jar%23467!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19.2-20220805.130853-srg.jar%23467!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddiumplus.mixin.json:darkness.GameRendererMixin,pl:mixin:APP:railways-common.mixins.json:client.MixinGameRenderer,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840) ~[client-1.19.2-20220805.130853-srg.jar%23467!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddiumplus.mixin.json:darkness.GameRendererMixin,pl:mixin:APP:railways-common.mixins.json:client.MixinGameRenderer,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23467!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23467!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23467!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23467!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.9.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
```
</details>

The second one is weirder because it would crash the world a few ticks after loading, and just say something like "Exit code -1" with no traceback. This was when I was trying to craft a LEU-235 fuel: the LEU-235 forming-press craft wasn't working, both the Gregtech-dust one and the Nuclearcraft one. I've seen this happen a few other times where a recipe doesn't work until a world reload, so I reloaded the world but then it would immediately crash.

This is all on beta 10 hotfix 4, which has Nuclearcraft Neoteric 1.03. The release notes for 1.04 say that it fixes multiple crashes, so maybe it's just a matter of updating, but the Nuclearcraft github lists a number of new 1.04+ crashes so I didn't try this. Honestly this mod seems not ready for use, and I only ended up using it because I saw the Nuclearcraft Pu241 chain before the Gregtech one, so it might be nice to mention the U238->tiny Pu239->Pu241 chain in the fusion reactor quest.

Otherwise, been liking the pack, thanks!

**Comment by kmod** [comment]
Oh and the Gregtech U238 centrifuge recipe conflicts with the one that makes the Nuclearcraft U238.

**Comment by Caerglad** [comment]
I also have simmilar issues with Nuclearcraft, while server was running it worked fine, but after restarting I'm getting errors from Ticking block entity.

Setting removeErroringBlockEntities forge flag to true stops crashes, but setting it back to false caused it to crash again.
Manualy removing fision reactor controllers fixed that

**Comment by Caerglad** [comment]
NC is to be removed in future version of the pack and replaced by custom GT multiblocks

**Comment by trulyno** [comment]
NC will be updated next version and removed the version after. That will probably fix the crash
